blueprint:
  name: PriceAnalyzer - Control Climate
  description: >-
    Based on (https://github.com/erlendsellie/priceanalyzer)
    Control a climate entity with PriceAnalyzer and an input number as a target temperature.
    The climate target temperature will update whenever input number is changed, or PriceAnalyzer updates.
    This Blueprint also requires two 'Multiply Correction', multiply up and multiply down. This is two input numbers where you can multiply the correction made by Priceanalyzer by for example 2 or 3
    
  domain: automation
  input:
    sensor:
      name: PriceAnalyzer
      description: PriceAnalyzer Sensor
      selector:
        entity:
          filter:
          - integration: priceanalyzer
            domain: sensor
    number:
      name: Base Setpoint Temperature
      description: Input Number Helper for base setpoint temperature
      selector:
        entity:
          filter:
            domain: input_number
    climate:
      name: Climate
      description: Climate Entity to control
      selector:
        entity:
          filter:          
            domain: climate
    multiply_up:
      name: Multiply Correction
      description: Input Number Helper To multiply the correction up. Useful if you want more aggressive control.
      selector:
        entity:
          filter:
            domain: input_number
    multiply_down:
      name: Multiply Correction
      description: Input Number Helper To multiply the correction down. Useful if you want more aggressive control.
      selector:
        entity:
          filter:
            domain: input_number
  source_url: https://github.com/erlendsellie/HomeAssistantConfig/blob/master/blueprints/automation/erlendsellie/priceanalyzer_multiply.yaml
mode: restart
max_exceeded: silent
trigger_variables:
  sensor: !input sensor
  number: !input number
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
      - !input sensor
      - !input number
      - !input multiply_up
      - !input multiply_down
action:
  - variables:
      sensor: !input sensor
      number: !input number
      climate: !input climate
      multiply_up: !input multiply_up
      multiply_down: !input multiply_down
  - condition: template
    value_template: "{{ states(climate) == 'heat' or states(climate) == 'off'}}"
  - service: climate.set_temperature
    data_template:
      entity_id: !input climate
      temperature: >-
        {%-set baseTemp = states(number) | float(default=0)%}
        {%-set priceanalyzer = states(sensor) | float(default=0)%}
        {% set multiplyNumberUp = states(multiply_up) | float(default=1)  %}
        {% set multiplyNumberDown = states(multiply_down) | float(default=1)  %}
        {% if priceanalyzer == 1 %}
        {{baseTemp + (priceanalyzer * multiplyNumberUp)}}
        {% elif priceanalyzer == -1 %}
        {{baseTemp + (priceanalyzer * multiplyNumberDown)}}
        {% else %}
        {{baseTemp}}
        {% endif %}
